set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(WINNOS_TRIPLE "x86_64-pc-winnos" CACHE STRING "WinnOS target triple")

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_ASM_NASM_COMPILER nasm)
set(CMAKE_AR llvm-ar)
set(CMAKE_RANLIB llvm-ranlib)
set(CMAKE_OBJCOPY llvm-objcopy)

set(CMAKE_C_COMPILER_TARGET ${WINNOS_TRIPLE})
set(CMAKE_CXX_COMPILER_TARGET ${WINNOS_TRIPLE})

set(WINNOS_COMMON_COMPILE_FLAGS "-ffreestanding -fno-stack-protector -fno-exceptions -fno-rtti -mno-red-zone")
set(WINNOS_COMMON_LINK_FLAGS "-fuse-ld=lld -nostdlib")

set(CMAKE_C_FLAGS_INIT "${WINNOS_COMMON_COMPILE_FLAGS} -Wall -Wextra")
set(CMAKE_CXX_FLAGS_INIT "${WINNOS_COMMON_COMPILE_FLAGS} -Wall -Wextra")
set(CMAKE_ASM_NASM_FLAGS_INIT "-f win64")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${WINNOS_COMMON_LINK_FLAGS}")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_EXECUTABLE_SUFFIX ".efi")
